[workspace]
members = [
    "contracts/*", 
    "library", 
    "tests/integration_tests",
    "tests/mocks/simple_dao"
]

[profile.release]
codegen-units = 1       
opt-level = "z"         
lto = true              
debug = false           
panic = "abort"         
overflow-checks = true
