[workspace]
members = ["contracts/dao", "contracts/dao_factory","contracts/workflow_provider", "library"]

[profile.release]
codegen-units = 1       
opt-level = "z"         
lto = true              
debug = false           
panic = "abort"         
overflow-checks = true
