[package]
name = "dao_factory"
version = "0.6.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # enable rlib for simulations tests, remove in prod


[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"

[dependencies.dao]
path = "../dao"

[features]
testnet = []