[package]
name = "dao_factory"
version = "0.6.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
near-sdk = {version = "4.0.0-pre.9", features = ["unstable"]}

[dependencies.dao]
path = "../dao"

[features]
testnet = []
