[package]
name = "dao"
version = "0.5.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"
library = { path = "./../../library", version = "0.1.0" }


[features]
testnet = []