[package]
name = "workflow_provider"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
library = { path = "./../../library", version = "0.1.0" }

[features]
testnet = []
