[package]
name = "workflow_provider"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = {version = "4.0.0-pre.7", features = ["unstable"]}
library = { path = "./../../library", version = "0.1.0" }

[features]
testnet = []
