[package]
name = "dao_factory"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"] # enable rlib for simulations tests, remove in prod


[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"

[dependencies.dao]
path = "../dao"

[dev-dependencies]
near-sdk-sim = "3.2.0"
