name: Build
on: 
  push: 
    branches:
      - 'main'
      - 'devel/next'
  pull_request:
    branches:
      - 'main'
      - 'devel/next'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cross-compile to Wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --target wasm32-unknown-unknown --release
